Latest boms
OpenHFT/Chronicle-Ticker pull request #5
Opened 2023-08-24 08:05 UTC by peter-lawrey

2023-08-24 12:31 UTC, alamar commented on pom.xml
> +        <version>1.24.0-SNAPSHOT</version>
I don't believe we should set it to SNAPSHOT or releasing would fail

2023-08-24 12:31 UTC, alamar commented on pom.xml
> +    <version>2.24ea1-SNAPSHOT</version>
Makes sense

2023-08-24 12:31 UTC, alamar commented on pom.xml
> +        <profile>
Could be done, but I've just brought `java11` profile back

2023-08-24 12:31 UTC, alamar commented on pom.xml
> +                <makefile>Makefile</makefile>
Should be Makefile11?

2023-08-24 12:31 UTC, alamar commented on pom.xml
> +                <makefile>Makefile</makefile>
Should be Makefile17?

2023-08-24 12:31 UTC, alamar commented on pom.xml
> +                <version>3.24.0-SNAPSHOT</version>
Would likely cause release to fail due to SNAPSHOT here

2023-08-24 12:31 UTC, alamar commented on src/main/c/Makefile17
> +# Makefile for C code
I don't believe we have build on Java17 currently (we test Java17 against code compiled by Java 8) so I'm not sure we would be able to test this.

2023-08-30 10:05 UTC, RobAustin reviewed
Ilya has already commented on this

2023-08-30 10:06 UTC, RobAustin requested changes
tests are failing 
![image](https://github.com/OpenHFT/Chronicle-Ticker/assets/6506056/e5c0b5a0-2ab6-429b-be9b-f88930045f4b)

2023-08-30 11:57 UTC, alamar commented
I believe we should archive this change for later, in case we ever need it.

2023-08-30 12:06 UTC, peter-lawrey commented
This has been replaced by some work Ilya did.

2023-08-30 12:06 UTC, closed without merging